* Emuvs

Olá visitante, este é o espaço de desenvolvimento de Everton Murilo Vieira.
Sou um programador e filósofo. Assim, as vezes escrevo algoritmos e estruturas de dados,
as vezes escrevo sobre a vida e as coisas. Meus interesses estão em informação e informática, 
conhecimento e epistemologia, inteligência e sabedoria. Todo o esforço que empenho nessa vida 
se dá em prol das finalidades desses campos.

* Projetos

Estes são os meus projetos atuais.

** AdMister

Interface gráfica escrita em React para administração de negócios.


** AdServer

Servidor para o AdMister escrito em Go com banco de dados Postgres.


** Pacmidia

Tendo em vista a carga enorme de documentos e arquivos multimídia que estão a nossa
disposicão nos dias de hoje é interessante ter um programa para auxiliar no seu
armazenamento, classificacão e recuperacão.

*** Características

 - [ ] Um conjunto de mídia é armezado dentro de uma pasta com os seus metadados.
 - [ ] Dois ou mais arquivos de mídia iguais devem ocupar um único espaco na raiz. 


* Poesias

** Duas Meninas na Vermelha

As meninas dancam sonoras no mar
livre sentem na pele o mar e a outra
na praia que é guardada da maioria.
